### ISSUE TITLE
404 for typescript definition file

### ISSUE THREAD

**Issue by nitsky** [pikapkg/cdn#3]
Hi, thanks for providing the pika cdn! It works great for me, except the typescript types for the `ts-interface-checker` npm package are not loading correctly.

The `package.json` specifies the typings like so: `"typings": "dist/index"`. The typings are located at `dist/index.d.ts`. The pika cdn, however, gives the following URL, which has one extra `index` directory in it:

```
https://cdn.pika.dev/-/ts-interface-checker@v0.1.10-mRbgItDLG0vLU9Ye5uF9/dist=es2019,mode=types/dist/index/index.d.ts
```

This URL returns a 404.

Browse the package here:
https://unpkg.com/browse/ts-interface-checker@0.1.10/

I believe the pika cdn has a bug with its handling of typescript type paths ending in "index". The typescript compiler has no problem with this package, and the `main` key is similarly specified but is handled correctly.

**Comment by FredKSchott** [comment]
fixed! Will push this fix out tonight, thanks for filing

**Comment by nitsky** [comment]
@FredKSchott I am still seeing this issue. As of this morning a request to:

```
/-/ts-interface-checker@v0.1.10-mRbgItDLG0vLU9Ye5uF9/dist=es2017,mode=types/index.d.ts
```

gives me a redirect to

```
/-/ts-interface-checker@v0.1.10-mRbgItDLG0vLU9Ye5uF9/dist=es2017,mode=types/dist/index/index.d.ts
```

**Comment by FredKSchott** [comment]
Thanks for the ping, fix was pushed but looks like the package needed to be rebuilt for the fix to be applied. 

That hashed resource will continue to point to the wrong type, but importing `ts-interface-checker` will now point to a fixed version.

**Comment by nitsky** [comment]
@FredKSchott importing `ts-interface-checker` directly gets me the correct hashed resource, but importing it indirectly through `https://cdn.pika.dev/sucrase@v3.14.0` still gets me the old hashed resource which has the bug. Is there some way to bust the cache?

**Comment by FredKSchott** [comment]
Hmm, yes that should have happened automatically when I rebuilt. Thanks for your patience on this, will fix it asap. 

As a workaround for now, you should be able to manually point to the correct types: 

```js
// @deno-types="https://cdn.pika.dev/-/ts-interface-checker@v0.1.10-YWqiZjggXn5A7DDTQ7Js/dist=es2019,mode=types/index.d.ts
import 'https://cdn.pika.dev/ts-interface-checker@v0.1.10';
```

**Comment by Nisgrak** [comment]
Hi! I have (i think) the same error with `xlsx`.

If I import the package it fails with 404 in
```
https://cdn.pika.dev/-/xlsx@v0.16.1-a1Z0nbCDHLEkThEqfqn3/dist=es2019,mode=types/types
```

The module correct url
```
https://cdn.pika.dev/-/xlsx@v0.16.1-a1Z0nbCDHLEkThEqfqn3/dist=es2019,mode=types/index.d.ts
```
redirects to
```
https://cdn.pika.dev/-/xlsx@v0.16.1-a1Z0nbCDHLEkThEqfqn3/dist=es2019,mode=types/types
```

**Comment by nitsky** [comment]
@FredKSchott I upgraded to a newer version of the `sucrase` package and am no longer observing the issue.

**Comment by bartlomieju** [comment]
Trying to import in Deno:
```
import {Button} from 'https://cdn.pika.dev/@material-ui/core@^4.10.1';
```
Downloading https://cdn.pika.dev/-/@material-ui/core@v4.10.1-fc2SiMnxs3PyrtZEG3jY/dist=es2019,mode=types/Card/Card.d.ts yields:
```ts
import * as React from '/-/react@v16.13.1-ByypZEPVPs6cpkpGdpQK/dist=es2019,mode=types/index.d.ts';
import { StandardProps } from '/../dist=es2019,mode=types/index.d.ts';
import { PaperProps } from '../Paper.d.ts';

export interface CardProps extends StandardProps<PaperProps, CardClassKey> {
  /**
   * If `true`, the card will use raised styling.
   */
  raised?: boolean;
}

export type CardClassKey = 'root';

/**
 *
 * Demos:
 *
 * - [Cards](https://material-ui.com/components/cards/)
 *
 * API:
 *
 * - [Card API](https://material-ui.com/api/card/)
 * - inherits [Paper API](https://material-ui.com/api/paper/)
 */
export default function Card(props: CardProps): JSX.Element;
```

Notice the second import: `/../dist=es2019,mode=types/index.d.ts` <--- effectively it always resolves to `https://cdn.pika.dev/dist=es2019,mode=types/index.d.ts`. 

I think that might be problem originating in Pika, @FredKSchott can you confirm that it's expected import specifier?

**Comment by FredKSchott** [comment]
Yup, we just fixed that bug this weekend. I updated to Deno v1.1.0 and all type imports now resolve successfully.

Note that it looks like you need to have the "dom" lib added in your tsconfig from material-ui to compile properly.
