### ISSUE TITLE
CSS files getting converted to JS

### ISSUE THREAD

**Issue by cletusw** [pikapkg/cdn#53]
[An example in the docs](https://docs.skypack.dev/lookup-urls/lookup-urls#lookup-a-package-file) shows a CSS file being loaded directly, but doing so actually results in a JS file.

Example from the docs: https://cdn.skypack.dev/bulma@latest/css/bulma.css

```
/*
 * Skypack CDN - bulma@0.9.0
 * 
 * Learn more:
 *   📙 Package Documentation: https://www.pika.dev/npm/bulma
 *   📘 Skypack Documentation: https://www.skypack.dev/docs
 * 
 * Pinned URL: (Optimized for Production)
 *   ▶️ Normal: Not Available. Import this URL to generate.
 *   ⏩ Minified: Not Available. Import this URL to generate.
 *
 */

// Browser-Optimized Imports (Don't directly import the URLs below in your application!)
export * from '/new/bulma@v0.9.0/dist=es2020/css/bulma.css';
export {default} from '/new/bulma@v0.9.0/dist=es2020/css/bulma.css';
```

Is there any way this could load the raw CSS instead?

Also related, the re-exported URL itself (https://cdn.skypack.dev/new/bulma@v0.9.0/dist=es2020/css/bulma.css) has an error as well, so this wouldn't work anyway:

```
/*
 * [Package Error] "bulma" could not be built. 
 * 
 *   ⠼ skypack installing... bulma
 *   ✖ skypack failed to load node_modules/bulma/bulma.sass
 *     Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
 * 
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/pikapkg/cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://pika.dev/ to find a web-friendly alternative to find another package.
 */

console.warn("[Package Error] \"bulma\" could not be built. \n⠼ skypack installing... bulma\n✖ skypack failed to load node_modules/bulma/bulma.sass\n  Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)");
throw new Error("[Package Error] \"bulma\" could not be built. ");
export default null;
```

I tried another package, and the file loads but still is being treated as a JS file.

https://cdn.skypack.dev/dialog-polyfill@0.5.3/dialog-polyfill.css

```
/*
 * Skypack CDN - dialog-polyfill@0.5.3
 * 
 * Learn more:
 *   📙 Package Documentation: https://www.pika.dev/npm/dialog-polyfill
 *   📘 Skypack Documentation: https://www.skypack.dev/docs
 * 
 * Pinned URL: (Optimized for Production)
 *   ▶️ Normal: https://cdn.skypack.dev/pin/dialog-polyfill@v0.5.3-2tQ1jZOU1KzgeqOIaED4/mode=raw/dialog-polyfill.css
 *   ⏩ Minified: https://cdn.skypack.dev/pin/dialog-polyfill@v0.5.3-2tQ1jZOU1KzgeqOIaED4/mode=raw,min/dialog-polyfill.css
 *
 */

// Browser-Optimized Imports (Don't directly import the URLs below in your application!)
export * from '/-/dialog-polyfill@v0.5.3-2tQ1jZOU1KzgeqOIaED4/dist=es2020,mode=raw/dialog-polyfill.css';
export {default} from '/-/dialog-polyfill@v0.5.3-2tQ1jZOU1KzgeqOIaED4/dist=es2020,mode=raw/dialog-polyfill.css';
```

https://cdn.skypack.dev/-/dialog-polyfill@v0.5.3-2tQ1jZOU1KzgeqOIaED4/dist=es2020,mode=raw/dist/dialog-polyfill.css

```
dialog {
  position: absolute;
  left: 0; right: 0;
  width: -moz-fit-content;
  width: -webkit-fit-content;
  width: fit-content;
  height: -moz-fit-content;
  height: -webkit-fit-content;
  height: fit-content;
  margin: auto;
  border: solid;
  padding: 1em;
  background: white;
  color: black;
  display: block;
}

...

export default null;
export const __esModule = true;
```

**Comment by drwpow** [comment]
Thanks for filing! Yes this is a known issue—we have a problem delivering packages that have no JS to build at all. We’ll be pushing out a fix for this soon; will update you on when this is fixed.

**Comment by cletusw** [comment]
Excellent, thanks!

**Comment by drwpow** [comment]
Update: we shipped an improvement to loading CSS files, which is now working. But we still have the remaining issue with Bulma where the package fails to build on Skypack because there’s no JS to process. This is still on our list of things to do. Thanks for your patience.

**Comment by drwpow** [comment]
Just checking in: we released a new version of the Skypack CDN which now supports Bulma. Both of these URLs should work:

```
https://cdn.skypack.dev/bulma
https://cdn.skypack.dev/bulma/css/bulma.min.css
```

Closing this issue as it‘s now been fixed, but please let us know if you experience any more difficulties.

**Comment by jonaskuske** [comment]
Hmm, plain URLs pointing at a CSS file still don't work:

https://cdn.skypack.dev/water.css/out/water.min.css

**Comment by drwpow** [comment]
That should work, but it looks like that package has a build error:

```js
const gulpfile = require('./gulpfile');
gulpfile.watch();

// Module \"./gulpfile\" could not be resolved by Skypack (Is it installed?)
```

If the `index.js` is fixed, then that CSS file could be served normally

**Comment by jonaskuske** [comment]
Hmm yeah, it doesn't publish it's build stuff to npm, just the artefacts (the CSS files in `out/`)

Does skypack only work if you publish all your build setup as part of the npm package?

**Comment by drwpow** [comment]
> Does skypack only work if you publish all your build setup as part of the npm package?

Sort of. Here, `water.css` has set `index.js` as its `"main"` entry, which indicates _this is the key file Skypack should load when importing `water.css`._ Skypack tries to build it, can‘t, and because the main entry failed Skypack assumes the rest of the package is broken.

Anyway, if this were just a random `.js` file in the project then Skypack probably wouldn‘t care as much, but because it‘s the main entry we throw an error.

So do you need to publish your build setup? Yes, if it‘s needed for the main package entry, as `water.css` has. But otherwise, no.

**Comment by jonaskuske** [comment]
I see!
So removing the `"main"` entry (or setting it to e.g. `./out/water.min.css`) should fix things?
I think `"main"` currently points at `index.js` because gulp uses that for its default task or something, but that should be avoidable. I'd prefer not to publish the entire build stuff if there's a way :)

**Comment by drwpow** [comment]
> So removing the `"main"` entry (or setting it to e.g. `./out/water.min.css`) should fix things?

Correct. As indicated by the [Node.js documentation](https://nodejs.org/api/packages.html#packages_main), this is the file that you’re saying _should_ be loaded in browsers when the package is imported. Which isn’t build setup.

My recommendation is to remove `"main"` altogether since it’s not JS. And prefer specific URLs for CSS like so: (e.g. ✅ `import 'cdn.skypack.dev/water.css/out/water.min.css'` rather than ❌ `import 'cdn.skypack.dev/water.css'`).

Skypack does support setting `"main"` to a `.css` file, but that’s not part of the ESM spec so that may break other tools. I’d advise against that (or, if you want to set it to _something_, many non-JS packages will export a stub JS file for `"main"`, e.g. an `index.js` file containing only `export default null`).
