### ISSUE TITLE
ESM module issue

### ISSUE THREAD

**Issue by Richienb** [pikapkg/cdn#64]
Due to a recent change, `ky-universal` is being tripped up: https://cdn.skypack.dev/-/ky-universal@v0.8.2-QbIKsCk80Svw4DXxasnr/dist=es2020/ky-universal.js

The contents of the url are:
```js
import __commonjs_module0 from '/-/ky@v0.24.0-LdGGAQxiyiz8l4V2kmD5/dist=es2020/ky.js';
export const {default} = __commonjs_module0;;


export default null;
export const __esModule = true;
```

Last time, this same module had received other (now fixed) problems: #4

**Comment by drwpow** [comment]
This seems like an error with Rollup’s CommonJS converter. I’ll look into fixing this on our end by updating our dependencies (likely an update to that caused the change in behavior you’re seeing).

In the meantime, it looks like it’s possible to import `https://cdn.skypack.dev/ky` directly? I’m not sure if `ky-universal` was doing anything to really prepare it for a browser anyway.

**Comment by Richienb** [comment]
`ky-universal` is imported by another module that I import myself.

**Comment by matthewp** [comment]
Hi @Richienb, we have a fix for `ky-universal` that should be released sometime soon. I'll update this thread when the fix is available.

**Comment by FredKSchott** [comment]
Fixed! We've added this package to our internal test suite so that we'll catch any future issues/regressions before release. 

```
await import('https://cdn.skypack.dev/ky-universal')
```

**Comment by Richienb** [comment]
@FredKSchott Great work! How long will it take until the fix is reflected in the CDN?

**Comment by matthewp** [comment]
Hey @Richienb, the release fixes the error reported in the issue. We have _another_ issue where we misidentify `ky` as CommonJS even though it is not. I spoke to soon in saying it was fixed. I'm working on some things in the next couple of weeks which will hopefully remove this false-negative code. Going to reopen the issue until the package is completely fixed.

**Comment by drwpow** [comment]
Update: I believe a recent update to the CDN has fixed this issue! I’m able to resolve `ky` and `ky-universal` in my browser now. But please let me know if I’m mistaken, or there’s still an issue outstanding.
