### ISSUE TITLE
[Package Issue] Wrongly resolved require paths

### ISSUE THREAD

**Issue by patrikholcak** [pikapkg/cdn#76]
Hey, 

I think I discovered a bug when trying to import
```js
const resolveConfig = import('https://cdn.skypack.dev/tailwindcss@1.9.6/resolveConfig')
```

<img width="1048" alt="Screenshot 2020-11-18 at 9 49 05" src="https://user-images.githubusercontent.com/72975/99507172-56e16a00-2983-11eb-8645-b4a5617f4dfb.png">

It resolves the couple of first modules, but then it gets the paths wrong.

It gets to file `https://cdn.skypack.dev/-/tailwindcss@v1.9.6-AmWpk4OpOvsq9fV4kCo4/dist=es2020,mode=raw/lib/util/getAllConfigs.js`

Which has these imports, which are mapped to wrong paths. eg. `./stubs/defaultConfig.stub.js` should be `../../stubs/defaultConfig.stub.js`

```
import require$$0 from './stubs/defaultConfig.stub.js';
import _featureFlags from './featureFlags';
import require$$1 from './flagged/uniformColorPalette.js';
import require$$2 from './flagged/extendedSpacingScale.js';
import require$$3 from './flagged/defaultLineHeights.js';
import require$$4 from './flagged/extendedFontSizeScale.js';
import require$$5 from './flagged/darkModeVariant.js';
import require$$6 from './flagged/standardFontWeights';
import require$$7 from './flagged/additionalBreakpoint';
import _lodash from '/-/lodash@v4.17.20-AK8bV2imBhL91nXpBIDu/dist=es2020/lodash.js';
```

I checked both the npm tarball and the source code and the paths appear to be ok:

https://github.com/tailwindlabs/tailwindcss/blob/8f3dbfe7a8be54c2afff46492dbf884c461ffa97/src/util/getAllConfigs.js#L1-L10

I even tried to change the url manually and the files resolve correctly: `https://cdn.skypack.dev/-/tailwindcss@v1.9.6-AmWpk4OpOvsq9fV4kCo4/dist=es2020,mode=raw/stubs/defaultConfig.stub.js`

Let me know if I can help in any way.

**Comment by FredKSchott** [comment]
Thanks for filing! This appears to be an issue in our "raw" mode CJS->ESM support. As a general rule, referencing a file directly within our package does impact our ability to optimize each package into a single file, and converting each file individually from CJS -> ESM is a bit tougher than converting the entire package at once.

But for this specific package, this seems more like an issue in our import URL resolver. Will take a deeper look and report back what we find.

**Comment by FredKSchott** [comment]
Fixed! Thanks again for filing

**Comment by patrikholcak** [comment]
@FredKSchott thank you for fixing it! The import now resolves correctly, but I’m still not able to call the function :(

// edit
Created 2 new issues
https://github.com/snowpackjs/skypack-cdn/issues/79
https://github.com/snowpackjs/skypack-cdn/issues/80
