### ISSUE TITLE
Module export is not callable when imported from another module

### ISSUE THREAD

**Issue by patrikholcak** [pikapkg/cdn#80]
Created from https://github.com/snowpackjs/skypack-cdn/issues/76#issuecomment-731099327

Hey, It’s me, again… sorry! I found this interesting thing - a module which causes error if imported from another module but doesn’t produce the same error if imported directly 🤷

### Steps to reproduce
```js
resolveConfig = await import('https://cdn.skypack.dev/tailwindcss@1.9.6/resolveConfig')
resolveConfig.default({ theme: { extend: {} }, variants: {}, plugins: [] })
```

Original file: https://github.com/tailwindlabs/tailwindcss/blob/8f3dbfe7a8be54c2afff46492dbf884c461ffa97/resolveConfig.js

### Expected result

the function doesn’t throw

### Actual result

Calling the imported function throws an error in the module:

<img width="640" alt="Screenshot 2020-11-20 at 11 51 39" src="https://user-images.githubusercontent.com/72975/99792140-f2f7a680-2b26-11eb-9c24-dbe09628e610.png">

---

More info

The file appears to import the module correctly:
```js
import require$$0 from "./lib/util/resolveConfig";
import require$$1 from "./lib/util/getAllConfigs";
const resolveConfigObjects = require$$0.default;
const getAllConfigs2 = require$$1.default;
var __VIRTUAL_FILE = function resolveConfig2(...configs) {
  const [, ...defaultConfigs] = getAllConfigs2(configs[0]);
  return resolveConfigObjects([...configs, ...defaultConfigs]);
};
export default __VIRTUAL_FILE;
```

Importing the module directly doesn’t produce the same error

<img width="635" alt="Screenshot 2020-11-20 at 22 22 43" src="https://user-images.githubusercontent.com/72975/99851144-f28afa00-2b7e-11eb-8151-89ad313c8321.png">

**Comment by drwpow** [comment]
Ah this is interesting! So it looks like the line in question that’s breaking is this:

```js
import require$$1 from "./lib/util/getAllConfigs";
```

Technically-speaking, ESM running in-browser requires file extensions (which Node doesn’t, so many people are used to omitting it). When you visit that URL directly in your browser, we redirect to the proper file. But the JavaScript doesn’t redirect properly, and it `404`s because of the missing `.js` file extension.

This is partially caused by tailwind not shipping [export maps](https://docs.skypack.dev/package-authors/package-checks#export-map) which allow Skypack to run ESM more efficiently. And it’s partially caused by Skypack not adding missing file extensions to JS at runtime. We could definitely look into better support for that.

**Comment by patrikholcak** [comment]
Let me know if I can help in any way - I don’t think the Tailwind guys are that much interested in it being able to run in browser (although there’s https://play.tailwindcss.com/) so not sure what I can do there. If it’s not fixable, then it’s not fixable. Thanks for looking into this!

**Comment by drwpow** [comment]
> I don’t think the Tailwind guys are that much interested in it being able to run in browser (although there’s https://play.tailwindcss.com/) so not sure what I can do there. If it’s not fixable, then it’s not fixable.

I will say in general, the npm community is still very much in the Node.js mindset (understandably so—npm is still technically meant for Node!). We do our best to prepare packages to run in a browser, but so many packages weren’t built with that consideration in mind, like you said.

In Tailwind’s case, though, fortunately I do think this is fixable! But on our end it’ll first take a larger improvement in the CDN that improves the way that JS modules within a package link to each other (as you saw, currently we upconvert CommonJS -> ESM as we’ve done here, but we need to take the next step and fix the module resolution as well, which is possible but can be tricky). It may take us a little time, but I’m hoping when that’s ready we’ll be able to fill in the gaps caused by tailwindcss’ current npm package and get it working in-browser.

Tailwind is a popular package, so I’d love to be able to get it working on Skypack!

**Comment by drwpow** [comment]
Update: this has been fixed! We were able to improve module resolution on our end and resolve the issue. I’m now able to load the code in the example above. Going to mark this as resolved, but please feel free to comment or re-open if I‘ve missed something.

**Comment by bradlc** [comment]
Hey @drwpow thanks for taking a look at this. I think the original issue is still present, unless I am misunderstanding. Here's a minimal reproduction: https://codesandbox.io/s/gallant-smoke-7eqr7?file=/index.html
